services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - .:/var/lib/db

  nodeapp:
    build:
      context: ./backend-space
    ports:
      - '9001:9000'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/spaces-api-dev
      SPACEAPI: https://api.spacexdata.com/v5

  frontapp:
    build:
      context: ./frontend-space
    ports:
      - '9002:5173'
    depends_on:
      - nodeapp
    environment:
      VITE_API_URL: http://localhost:9001
